# Generated by Django 5.0.6 on 2024-06-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_activivacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emitida', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('id_estado', models.CharField(choices=[], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado_despacho', models.CharField(choices=[], max_length=1)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.CharField(choices=[('T', 'Transferencia'), ('C', 'Tarjeta'), ('E', 'Efectivo')], max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('cantidad_compras', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='id_boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.boleta'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pago'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='productos',
            field=models.ManyToManyField(to='tienda.producto'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ManyToManyField(to='tienda.producto'),
        ),
    ]
