# Generated by Django 5.0.6 on 2024-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_administrador_boleta_categoria_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
