# Generated by Django 5.0.6 on 2024-06-24 07:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emitida', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('iva', models.IntegerField()),
                ('total_neto', models.IntegerField()),
                ('total_a_pagar', models.IntegerField()),
                ('estado_pago', models.CharField(choices=[('P', 'Pagado'), ('N', 'No Pagado'), ('E', 'Pendiente')], default='E', max_length=1)),
                ('estado_despacho', models.CharField(choices=[('D', 'Despachado'), ('N', 'No Despachado'), ('R', 'Recibido')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.CharField(choices=[('T', 'Transferencia'), ('C', 'Tarjeta'), ('E', 'Efectivo')], max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=150)),
                ('imagen', models.ImageField(blank=True, default='productos/icono.jpeg', null=True, upload_to='productos')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=8, null=True)),
                ('username', models.CharField(default='usuario', max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('TipoPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.pago')),
            ],
        ),
    ]
