# Generated by Django 5.0.6 on 2024-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/icono.jpeg', null=True, upload_to='productos'),
        ),
    ]
