# Generated by Django 5.0.6 on 2024-06-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuario_contraseña_alter_administrador_fecha_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_compras',
        ),
    ]
