# Generated by Django 5.0.6 on 2024-06-24 02:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='productos',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emitida',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total_neto', models.IntegerField()),
                ('total_a_pagar', models.IntegerField()),
                ('estado_pago', models.CharField(choices=[('P', 'Pagado'), ('N', 'No Pagado'), ('E', 'Pendiente')], default='E', max_length=1)),
                ('estado_despacho', models.CharField(choices=[('D', 'Despachado'), ('N', 'No Despachado'), ('R', 'Recibido'), ('C', 'Cancelado')], default='N', max_length=1)),
                ('productos', models.JSONField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.boleta')),
            ],
        ),
        migrations.DeleteModel(
            name='detalle_boleta',
        ),
    ]
