# Generated by Django 5.0.6 on 2024-06-23 18:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_delete_administrador_remove_boleta_id_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='id_Usuario',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='neto',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emitida',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('estado', models.CharField(choices=[], max_length=1)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle_compra',
        ),
    ]
