# Generated by Django 5.0.6 on 2024-06-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='neto',
        ),
    ]
