# Generated by Django 5.0.6 on 2024-06-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_boleta_id_estado_remove_boleta_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(choices=[], max_length=1)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle_compra',
        ),
    ]
