# Generated by Django 5.0.6 on 2024-06-23 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_detalle_boleta_delete_detalle_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emitida',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
