# Generated by Django 5.0.6 on 2024-06-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_boleta_fecha_emitida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_boleta',
            old_name='total',
            new_name='subtotal',
        ),
    ]
