# Generated by Django 5.0.6 on 2024-06-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_boleta_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='id_pago',
        ),
    ]
