# Generated by Django 5.0.6 on 2024-06-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_boleta_id_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='precio',
        ),
    ]
